### ISSUE TITLE
Tool stops working after requesting websocket handshake.

### ISSUE THREAD

**Issue by akaAMAZING** [xenial/tradesniper_poe#1]
http://prntscr.com/p40o30

Please refer to the image above.

Attempted it with Blight and then also Legion just to troubleshoot since your example was showing Legion.

Thank you.

**Comment by xenial** [comment]
I'll try it out and attempt to troubleshoot it after 3.8.0d is out, thanks for letting me know about this.

**Comment by akaAMAZING** [comment]
You're welcome buddy. Let me know when you're ready for me to test it out again.

**Comment by xenial** [comment]
Should be fixed now.

**Comment by akaAMAZING** [comment]
Hi there, gave it another try. Did get another line before it stopped functioning.

http://prntscr.com/p4enip

**Comment by xenial** [comment]
Try deleting your config.json file and resetting your poesessid.

**Comment by xenial** [comment]
https://i.imgur.com/8CDjqyf.png

Should look like that, if it still doesn't work try downloading and running the release from [here](https://github.com/xen1al/tradesniper_poe/releases/latest)

**Comment by akaAMAZING** [comment]
I've tried running that release too. It just closes out after the successful handshake so I had nothing to screenshot and that's why I used CMD instead.

http://prntscr.com/p4f55p

**Comment by xenial** [comment]
Did you grab a new poesessid? I'm pretty sure it's just instantly closing the websocket since the poesessid is incorrect, atleast that's what has happened to me. I'm still cracking down on bugs so it's still not perfect, but that's the only thing I can come up with right now.

**Comment by akaAMAZING** [comment]
The POESESSID is correct. I pulled it a moment ago from the official website. I have also used the same ID for a different tool which works but is fairly clunky as it was only able to search one item at a time and so was hoping to make use of yours.

If you want to check it out for ideas here it is:

https://github.com/vlameiras/poe-trade-parser

Please let me know if you want me to remove the above link as it may be a conflict of interest. Just thought you may like to see it to troubleshoot.

Thank you!

**Comment by xenial** [comment]
I'm pretty sure I figured it out: from looking at your pictures I can tell the poesessid is in incorrect format. Just enter POESESSID=**the poesessid from your cookies tab**.

This is entirely my bad, should've addressed it in the readme. I'll fix it tomorrow, It's getting late here. 

Edit: in case you're wondering why it's like that, I'm used to copying my poesessid from the request headers tab, not the cookies tab.

**Comment by akaAMAZING** [comment]
Yes I know how to find the correct POESESSID and I apologize for hiding it. I am copy and pasting it from here after logging out and back in:

http://prntscr.com/p4fjep

http://prntscr.com/p4fk5c

**Comment by akaAMAZING** [comment]
Oh I understand, you want me to include 'POESESSID=' in the field. It seems to be working now :)

http://prntscr.com/p4flcy

Great, thank you so much!

**Comment by xenial** [comment]
Yeah, my bad. It should work if you just put "POESESSID=" before the actual poesessid. And you should hide your poesessid, that's not something you want others to see. Let me know if it works now.

**Comment by xenial** [comment]
Thanks for being patient with me, closed.
